#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/dugadesk/dugadesk /usr/bin/dugadesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/dugadesk.service ]; then
			rm /etc/systemd/system/dugadesk.service /usr/lib/systemd/system/dugadesk.service /usr/lib/systemd/user/dugadesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/dugadesk/files/systemd/dugadesk.service /usr/lib/systemd/system/dugadesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload dugadesk.service: Unit dugadesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/dugadesk.service:10: Executable path is not absolute: pkill -f "dugadesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/dugadesk.service
		fi
		systemctl daemon-reload
		systemctl enable dugadesk
		systemctl start dugadesk
	fi
fi
