#!/bin/bash

set -e

case $1 in
    remove|upgrade)
		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
		rm -f /usr/bin/dugadesk
		
		if [ "systemd" == "${INITSYS}" ]; then

			systemctl stop dugadesk || true
			systemctl disable dugadesk || true
			rm /etc/systemd/system/dugadesk.service /usr/lib/systemd/system/dugadesk.service || true
			
			# workaround temp dev build between 1.1.9 and 1.2.0
			serverUser=$(ps -ef | grep -E 'dugadesk +--server' | grep -v 'sudo ' | awk '{print $1}' | head -1)
			if [ "$serverUser" != "" ] && [ "$serverUser" != "root" ]
			then
				systemctl --machine=${serverUser}@.host --user stop dugadesk >/dev/null 2>&1 || true
			fi
			rm /usr/lib/systemd/user/dugadesk.service >/dev/null 2>&1 || true
		fi
        ;;
esac

exit 0
